### ISSUE TITLE
reproducibility of the results

### ISSUE THREAD

**Issue by yaoli** [alshedivat/adios#1]
Thanks for the contribution. I really enjoy reading the paper, especially the graphical model part.

On the other hand, I find it hard to run the code without any instruction of getting the datasets. Among those used, I'm most interested in BIOASQ. Is there a way you could make it available so that  I execute the code? 

I also have a new idea to experiment. It would be nice to use the same preprocessed BIOASQ dataset. 

Thanks in advance.

**Comment by alshedivat** [comment]
It's great to hear that you enjoyed reading our paper!

For the reproducibility, you should be able to replicate our experiments on Delicious and MediaMill.

For the BioASQ dataset, it is publically available (I believe, after some formal registration). I'd be glad to share the pre-processing scripts with you, but be aware that that code has never been cleaned or even touched after the features and labels were extracted. Alternatively, I could share already preprocessed features (2.3 GB) and labels (31 MB).

**Comment by yaoli** [comment]
Thanks for the reply. Yes, I just noticed that the provided code is indeed ready for Delicious and MediaMill. Meanwhile, if it's not too much of a trouble, could you make the aforementioned BioASQ available as well?

**Comment by alshedivat** [comment]
Sure, you can download the features and labels from the following links: [features.npy](https://yadi.sk/d/WvwBSg963E8sMq) and [labels.pkl](https://yadi.sk/d/zfKrkoDn3E8sDw).
